### ISSUE TITLE
sdkClientSecret not updating on `configs` change

### ISSUE THREAD

**Issue by kienngo98** [paperxyz/js-sdk#106]
I have an NFT Drop contract from Thirdweb. Before the recent update (backend-less checkout element), I would call an API to fetch the sdkClientSecret like this:
```
const postData: any = {
    contractId: contractId,
    walletAddress: walletAddress,
    quantity: quantity, // <--------------------- This was working well
  };

  const options = {
    method: 'POST',
    headers: {
      accept: 'application/json',
      'content-type': 'application/json',
      Authorization: `Bearer ${process.env.PAPER_XYZ_API_KEY}`,
    },
    body: JSON.stringify(postData),
  };

  const result = await fetch('https://withpaper.com/api/2022-08-12/checkout-sdk-intent', options).then((response) =>
    response.json(),
  );
```

With the recent update, I don't have to call the API anymore, instead I can just do this:
```
<CheckoutWithCard
  configs={{
    contractId: contractId,
    walletAddress: address,
    email,
    quantity: mintQty, // <----------------------- NOT WORKING
  }}
/>
)}
```

Here's the front-end code:
```
...
// There are 2 buttons which will increase and decrease the `mintQty`
const [mintQty, setMintQty] = useState<number>(1);
...
return (
  <CheckoutWithCard
    configs={{
      contractId: contractId,
      walletAddress: address,
      email,
      quantity: mintQty, // <----------------------- NOT WORKING
    }}
  />
);
```
Front-end preview:
![image](https://github.com/paperxyz/js-sdk/assets/26052673/1905d361-8a1f-4767-9418-a9bcab7c59e6)

Expected result:
```
Whenever mintQty change, the <CheckoutWithCard /> should fetch new sdkClientSecret.
```

**Comment by mathieu-bour** [comment]
A possible workaround would be to use the old `sdkClientSecret` field. Basically, the `configs` is encoded and used as client secret using the following function:

https://github.com/paperxyz/js-sdk/blob/30172ea73d5de9c55f12d3c4b9e8c9e0bc6d8f0f/packages/js-client-sdk/src/lib/CheckoutWithCard.ts#L54-L57


In your case:

```tsx
<CheckoutWithCard sdkClientSecret={btoa(JSON.stringify(configs))} />
```

**Comment by kienngo98** [comment]
Hi @mathieu-bour, thanks for the suggestion. Unfortunately this doesn't seem to fix it for me.

**Comment by mathieu-bour** [comment]
I just read your initial issue more carefully, but the `CheckoutWithCard` won't fetch any secret when using config, because the `sdkClientSecret` is now the base64 of the stringified `configs` payload. `CheckoutWithCard` will basically send the `configs` payload when click on the "Pay" button.

**Comment by kienngo98** [comment]
I think I got the solution (thanks to your suggestion).

Before:
```
<PaperWrapper mintQty={mintQty} /> // <--- NOT WORKING
```

After:
```
<PaperWrapper key={mintQty} mintQty={mintQty} /> // <--- WORKING
```

So the key here (no pun intended) is to use the key props to force React to re-render the component every time mintQty changes
