### ISSUE TITLE
Wrong getPaperOriginUrl default value

### ISSUE THREAD

**Issue by qruz-hq** [paperxyz/js-sdk#176]
I'm guessing this was overlooked while migrating payment links to thirdweb domains.

The actual default Paper origin url is `https://payments.thirdweb.com` not `https://withpaper.com`.

This is preventing modals with message handlers to work properly and firing `paymentSuccess` and `claimSuccessful` events. In my opinion this is top priority

https://github.com/paperxyz/js-sdk/blob/5615875f9f624fa435be2f96619fa101da13af00/packages/sdk-common-utilities/src/constants/settings.ts#L15

**Comment by qruz-hq** [comment]
This PR should fix it
https://github.com/paperxyz/js-sdk/pull/177

**Comment by warengonzaga** [comment]
Hey @gerrysaporito can you check this? Thanks!

**Comment by ElasticBottle** [comment]
Hey @qruz-hq you should be using the sdk in the thirdweb package, Thanks!

**Comment by qruz-hq** [comment]
> Hey @qruz-hq you should be using the sdk in the thirdweb package, Thanks!

Does this mean this package is deprecated? 

Edit: I checked the thirdweb sdk and there's no replacement for the "renderPaperCheckoutLink" fuction. I'll stick to this package and implemented my extra message listeners to get around this. Will update to thirdweb packages when it has the same feature.
